name: 'NPM Custom action'
description: 'Installing and caching NPM Packages'
inputs:
 path-to-cache:
    description: 'the path to cache'
    required: true
runs:
 using: 'composite'
 steps:
     - name: Cache NPM dependencies
       uses: actions/cache@v4
       with:
         path: node_modules
         key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }
     - name: Install Dependecies
       run: npm install 
   