name: Reuseable Deployment Workflow

on:
    workflow_call: 

jobs:
    reuse-deploy:
        environment:
          name: development
          url:  https://${{steps.set-ingress-host-address.outputs.APP_INGRESS_HOST}}
        outputs:
          APP_INGRESS_URL: ${{steps.set-ingress-host-address.outputs.APP_INGRESS_HOST}}
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Install Kubectl
              uses: azure/setup-kubectl@v4
              with:
                version: 'v1.31.8'
            - uses: azure/login@v2
              with:
                 client-id: ${{ secrets.AZURE_CLIENT_ID }}
                 tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                 subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            - uses: azure/aks-set-context@v4
              with:
                 resource-group: ${{ vars.RG_NAME}}
                 cluster-name: ${{vars.CLUSTER_NAME}}             
            - name: Fetch Kubernetes Cluster Details
              run: |
                 kubectl version
                 echo -----------------------------------------
                 kubectl get nodes
            - name: Save the Ingress IP as Env variable
              run: |

            - name: Replace Tokens in Manifest files
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '_{_'
                tokenSuffix: '_}_'
                files: '["kubernetes/development/*.yaml"]'
              env:
                NAMESPACE: ${{ vars.NAMESPACE}}
                REPLICAS: ${{ vars.REPLICAS}}
                DNS: ${{ secrets.DNS}}
                IMAGE: ghcr.io/${{ github.repository_owner}}/solar-system:${{github.sha}}

            - name: Check Files
              run: |
               cat kubernetes/development/*.yaml
             
            - name: Create MangoDB Secret.
              run: | 
               kubectl -n ${{vars.NAMESPACE}} create secret generic mongo-db-creds \
               --from-literal=MONGO_URI=${{ vars.MONGO_URI }} \
               --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
               --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD}} \
               --save-config \
               --dry-run=client \
               -o yaml | kubectl apply -f -

            - name: Deploy to DEV NAMSPACE oF CLUSTER
              run: | 
               kubectl apply -f kubernetes/development
            - name: Set APP Ingress Host URL
              id: set-ingress-host-address
              run: |
               echo "APP_INGRESS_HOST=solar-system-${{vars.NAMESPACE}}.${{ vars.DNS}}" >> "$GITHUB_OUTPUT"