name: Reuseable Deployment Workflow

on:
    workflow_call:
      inputs:
        k8s-manifest-dir:
         description: Kubernetes Manifest Directory
         required: true
         default: kubernetes/
         type: string
        environment: 
         description: Provide the environment name to Deploy
         required: true
         type: string
      outputs:
        application-url:
          value: ${{ jobs.reuse-deploy.outputs.APP_INGRESS_HOST}}

jobs:
    reuse-deploy:
        environment:
          name: ${{ inputs.environment }}
          url:  https://${{steps.set-ingress-host-address.outputs.APP_INGRESS_HOST}}
        outputs:
          APP_INGRESS_URL: ${{steps.set-ingress-host-address.outputs.APP_INGRESS_HOST}}
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Install Kubectl
              uses: azure/setup-kubectl@v4
              with:
                version: 'v1.31.8'
            - uses: azure/login@v2
              with:
                 client-id: ${{ secrets.AZURE_CLIENT_ID }}
                 tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                 subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            - uses: azure/aks-set-context@v4
              with:
                 resource-group: ${{ vars.RG_NAME}}
                 cluster-name: ${{vars.CLUSTER_NAME}}             
            - name: Fetch Kubernetes Cluster Details
              run: |
                 kubectl version
                 echo -----------------------------------------
                 kubectl get nodes
            - name: Save the Ingress IP as Env variable
              run: |

            - name: Replace Tokens in Manifest files
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '_{_'
                tokenSuffix: '_}_'
                files: '["${{ inputs.k8s-manifest-dir}}*.yaml"]'
              env:
                NAMESPACE: ${{ vars.NAMESPACE}}
                REPLICAS: ${{ vars.REPLICAS}}
                DNS: ${{ secrets.DNS}}
                IMAGE: ghcr.io/${{ github.repository_owner}}/solar-system:${{github.sha}}

            - name: Check Files
              run: |
               cat ${{ inputs.k8s-manifest-dir}}*.yaml
             
            - name: Create MangoDB Secret.
              run: | 
               kubectl -n ${{vars.NAMESPACE}} create secret generic mongo-db-creds \
               --from-literal=MONGO_URI=${{ vars.MONGO_URI }} \
               --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
               --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD}} \
               --save-config \
               --dry-run=client \
               -o yaml | kubectl apply -f -

            - name: Deploy to ${{ vars.NAMESPACE}} oF CLUSTER
              run: | 
               kubectl apply -f ${{ inputs.k8s-manifest-dir}}
            - name: Set APP Ingress Host URL
              id: set-ingress-host-address
              run: |
               echo "APP_INGRESS_HOST=solar-system-development.${{ vars.DNS}}" >> "$GITHUB_OUTPUT"